version: '3.7'
services:
  php:
    image: dvlpm/php8.1-dev:latest
    volumes:
      - ./:/var/www/html
      - ./volumes/php/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - composer:/var/www/.composer
    environment:
      XDEBUG_CONFIG: client_host=${DEBUG_CLIENT_HOST} log_level=0
      PHP_IDE_CONFIG: serverName=${DEBUG_SERVER_NAME}

volumes:
  composer:
